src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Entity\ContenuPanier;
use App\Repository\PanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PanierRepository::class)]
class Panier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'paniers')]
    #[ORM\JoinColumn(nullable: false)]
    private $utilisateur;

    #[ORM\Column(type: 'datetime',  nullable: true)]
    private $date_achat;

    #[ORM\Column(type: 'boolean')]
    private $etat;

    #[ORM\OneToMany(mappedBy: 'panier', targetEntity: ContenuPanier::class)]
    private $contenuPaniers;

    public function __construct()
    {
        $this->contenuPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?user
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?user $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection<int, ContenuPanier>
     */
    public function getContenuPaniers(): Collection
    {
        return $this->contenuPaniers;
    }

    public function addContenuPanier(ContenuPanier $contenuPanier): self
    {
        if (!$this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers[] = $contenuPanier;
            $contenuPanier->setPanier($this);
        }

        return $this;
    }

    public function removeContenuPanier(ContenuPanier $contenuPanier): self
    {
        if ($this->contenuPaniers->removeElement($contenuPanier)) {
            // set the owning side to null (unless already changed)
            if ($contenuPanier->getPanier() === $this) {
                $contenuPanier->setPanier(null);
            }
        }

        return $this;
    }

    public function getTotal(){

        $contenuPaniers = $this->contenuPaniers;
        $total = 0;

        foreach($contenuPaniers as $contenuPanier){

            $total += $contenuPanier->getMontant();

        }
      
        return $total;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'string', length: 255)]
    private $prenom;

    #[ORM\OneToMany(mappedBy: 'utilisateur', targetEntity: Panier::class)]
    private $paniers;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(type: 'datetime',  nullable: true)]
    private $dateCreation;

    public function __construct()
    {
        $this->paniers = new ArrayCollection();
        $this->dateCreation = new \DateTime(date('Y-m-d'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }


    /**
     * @return Collection<int, Panier>
     */
    public function getPaniers(): Collection
    {
        return $this->paniers;
    }

    public function addPanier(Panier $panier): self
    {
        if (!$this->paniers->contains($panier)) {
            $this->paniers[] = $panier;
            $panier->setUtilisateur($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): self
    {
        if ($this->paniers->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getUtilisateur() === $this) {
                $panier->setUtilisateur(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function __toString()
    {
        return $this->email;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('password')
            ->add('nom')
            ->add('prenom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;       
use App\Entity\ContenuPanier;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Repository\PanierRepository;
use App\Repository\ContenuPanierRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

#[Route('/user')]
class UserController extends AbstractController
{
    // Permet de récupérer les commandes de l'utilisateur ainsi que son profil
    #[Route('/profil', name: 'user_index')]
    public function index(UserRepository $userRepository, PanierRepository $panierRepository, TranslatorInterface $t): Response
    {
        $user = $this->getUser();
        $commandes = $panierRepository->findBy(['utilisateur' => $user, 'etat' => true]);
        return $this->render('user/index.html.twig', [
            'commandes' => $commandes
        ]);
    }

    // Permet de récupérer les commandes qui n'ont pas été payé par tous les utilisateurs
    #[Route('/non_commande', name: 'non_commande', methods: ['GET', 'POST'])]
    public function nonCommande(Request $request, PanierRepository $panierRepository, ContenuPanierRepository $contenuPanierRepository, EntityManagerInterface $entityManager, TranslatorInterface $t): Response
    {
        // Récuperation du panier
        $panier = $panierRepository->findBy(['etat' => false]);

        // Récupération des produits dans le panier
        $contenuPanier = $contenuPanierRepository->findBy(['panier' => $panier]);

        return $this->render('user/non_commande.html.twig', [
            'panier' => $panier,
        ]);
    }

    // Permet de récupérer les commandes qui n'ont pas été payé par tous les utilisateurs
    // #[Route('/non_commande', name: 'non_commande')]
    // public function nonCommande(UserRepository $userRepository, PanierRepository $panierRepository): Response
    // {
    //     $user = $this->getUser();
    //     $commandes = $panierRepository->findBy(['utilisateur' => $user, 'etat' => false]);
    //     return $this->render('user/non_commande.html.twig', [
    //         'user' => $user,
    //         'commandes' => $commandes
    //     ]);
    // }

    // Permet de récupérer les utilisateurs inscrit aujourd'hui du plus récent au plus ancien
    #[Route('/user_now', name: 'user_now')]
    public function userNow(UserRepository $userRepository, PanierRepository $panierRepository, TranslatorInterface $t): Response
    {
        $user = $userRepository->findBy(array('dateCreation' => new \DateTime(date('Y-m-d'))),array('id' => 'DESC'));
        return $this->render('user/user_now.html.twig', [
            'user' => $user,
        ]);
    }

    // Permet de s'inscrire sur le site
    #[Route('/new', name: 'user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, TranslatorInterface $t): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    // Permet de l'utilisateur
    #[Route('/{id}', name: 'user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    // Permet d'éditer le profil de l'utilisateur
    #[Route('/{id}/edit', name: 'user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager, TranslatorInterface $t): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView()
        ]);
    }

    // Permet de supprimer un utilisateur
    #[Route('/{id}', name: 'user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager, TranslatorInterface $t): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }

    // Permet de récupérer les commandes qui ont été payées par l'utilisateur
    #[Route('/commande/{id}', name: 'user_commande', methods: ['GET', 'POST'])]
    public function userCommande(Request $request, PanierRepository $panierRepository, ContenuPanierRepository $contenuPanierRepository, EntityManagerInterface $entityManager, TranslatorInterface $t): Response
    {
        // Id de la commande dans la route
        $idCommande = $request->attributes->get('id');

        // Récuperation du panier
        $panier = $panierRepository->findOneBy(['id' => $idCommande]);

        // Récupération des produits dans le panier
        $contenuPanier = $contenuPanierRepository->findBy(['panier' => $panier]);
        return $this->render('user/commande.html.twig', [
            'idCommande' => $idCommande,
            'contenu_panier' => $contenuPanier,
            'panier' => $panier
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('"{{ 'user.alertDeleteUser'|trans }}"');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">{{ 'user.deleteUser'|trans }}</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ 'user.formEnregistrer'|trans }}</button>
{{ form_end(form) }}

templates/user/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'user.commandeTitle'|trans }}{% endblock %}

{% block body %}
	<h1>{{ 'user.commandeH1'|trans }}</h1>

	<div class="row">
		<div class="col-md-8 order-md-2 mb-8">
			{% if contenu_panier is not empty %}
				<h4 class="d-flex justify-content-between align-items-center mb-3">
					<span class="text-muted">{{ 'user.commandeDetaiil'|trans }}</span>
				</h4>
				<ul class="list-group mb-3">
					{% set total = 0 %}
					{% for p in contenu_panier %}
						{% set totalProduit = 0 %}
						{% set totalProduit = p.produit.prix * p.quantite %}
						{% set total = total + (p.produit.prix * p.quantite) %}
                        {{ panier.dateAchat|date("d/m/Y h:i:s") }}
						<li class="list-group-item d-flex justify-content-between lh-condensed">
							<div>
								<h6 class="my-0">{{ p.produit.nom }}</h6>
								<small class="text-muted">{{ p.produit.prix }}
									{{ 'user.commandeEuro'|trans }} {{ 'user.commandeX'|trans }}
									{{ p.quantite }}</small>
							</div>
							<span class="text-muted">
								{{ totalProduit}}
								€
							</span>
						</li>
					{% endfor %}
					<li class="list-group-item d-flex justify-content-between">
						<span class="">{{ 'user.commandeNbTotalProd'|trans }} : <b>{{ contenu_panier|length }}</b></span>
					</li>					
					<li class="list-group-item d-flex justify-content-between" style="font-size:20px;padding-bottom:40px;padding-top:20px;">
						<span>{{ 'user.commandeMontantTotal'|trans }} : </span>
						<span style="color:#b12704;font-weight:bold;">{{ total }} {{ 'user.commandeEuro'|trans }}</span>
					</li>
				</ul>
			</div>
			<div class="col-md-8 order-md-1">
			{% else %}
				<p>{{ 'user.commandePanierVide'|trans }}</p>
                <a href="{{ path('produit_index') }}" class="btn btn-primary">{{ 'user.commandeContinuerAchat'|trans }}</a>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'user.editTitle'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'user.editH1'|trans }}</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">{{ 'user.editReturnList'|trans }}</a>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'user.indexTitle'|trans }}{% endblock %}


{% block body %}
    <h1 style="padding-bottom:30px;">{{ 'user.indexH1'|trans }}{</h1>

    <div style="font-size:20px;font-weight:bold;padding-bottom:20px;color:blue;">{{ 'user.indexBonjourM'|trans }}{ {{ app.user.nom }} {{ app.user.prenom }} {{ 'user.indexBienvenue'|trans }} </div>
    <table class="table">
        <thead>
            <tr>
                <th>{{ 'user.indexId'|trans }}</th>
                <th>{{ 'user.indexNom'|trans }}</th>
                <th>{{ 'user.indexPrenom'|trans }}</th>
                <th>{{ 'user.indexEmail'|trans }}</th>
                <th>{{ 'user.indexPassword'|trans }}</th>
                <th>{{ 'user.indexRoles'|trans }}</th>
                <th>{{ 'user.indexActions'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% if app.user %}
            <tr>
                <td>{{ app.user.id }}</td>
                <td>{{ app.user.nom }}</td>
                <td>{{ app.user.prenom }}</td>
                <td>{{ app.user.email }}</td>
                <td>{{ app.user.password }}</td>
                <td>{{ app.user.roles ? app.user.roles|json_encode : '' }}</td>
                <td>
                    <a href="{{ path('user_edit', {'id': app.user.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">{{ 'user.indexNoUserFound'|trans }}</td>
            </tr>
        {% endif %}
        </tbody>
    </table>





    <h1 style="padding-bottom:30px;padding-top:30px;">{{ 'user.indexH12'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{ 'user.indexId2'|trans }}</th>
                <th>{{ 'user.indexMontant2'|trans }}</th>
                <th>{{ 'user.indexDate2'|trans }}</th>
                <th>{{ 'user.indexActions2'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% for c in commandes %}
            <tr>
                <td>{{ c.id }}</td>
                <td>{{ 'user.indexMontantAFaire'|trans }}</td>
                <td>{{ c.dateAchat|date('d/m/Y h:i:s') }}</td>
                <td>
                    <a href="{{ path('user_commande', {'id': c.id}) }}"><i class="fa-solid fa-eye"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">{{ 'user.indexNoCommandFound'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'user.newTitle'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'user.newH1'|trans }}</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">{{ 'user.newReturnList'|trans }}</a>
{% endblock %}

templates/user/non_commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'noCommand.noCommandTitle'|trans }}{% endblock %}


{% block body %} 


<h1 style="padding-bottom:30px;padding-top:30px;">{{ 'noCommand.noCommandH1'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th style="width:33%;">{{ 'noCommand.noCommandUtilisateur'|trans }}</th>
                <th style="width:33%;">{{ 'noCommand.noCommandNumeroPanier'|trans }}</th>
                <th style="width:33%;">{{ 'noCommand.noCommandContenuPanier'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% for p in panier %}
            <tr>
                <td>{{ p.utilisateur }}</td>
                <td>{{ p.id }}</td>

                {# {% for c in contenuPaniers %}
                    <td>{{ c.id.produit }}</td>
                {% endfor %} #}

            </tr>
        {% else %}
            <tr>
                <td colspan="8">{{ 'noCommand.noCommandNoPanierNoPaid'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %} 

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'user.showTitle'|trans }}{% endblock %}

{% block body %}
    <h1>{{ 'user.showH1'|trans }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>{{ 'user.showId'|trans }}</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>{{ 'user.showEmail'|trans }}</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>{{ 'user.showRoles'|trans }}</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>{{ 'user.showPassword'|trans }}</th>
                <td>{{ user.password }}</td>
            </tr>
            <tr>
                <th>{{ 'user.showNom'|trans }}</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>{{ 'user.showPrenom'|trans }}</th>
                <td>{{ user.prenom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_index') }}">{{ 'user.showReturnList'|trans }}</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">{{ 'user.showEdit'|trans }}</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/user_now.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des paniers non achetés{% endblock %}


{% block body %}

    <h1 style="padding-bottom:30px;padding-top:50px;">{{ 'user.userTitle'|trans }}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{{ 'user.userId'|trans }}</th>
                <th>{{ 'user.userNom'|trans }}</th>
                <th>{{ 'user.userPrenom'|trans }}</th>
                <th>{{ 'user.userEmail'|trans }}</th>
                <th>{{ 'user.userPassword'|trans }}</th>
            </tr>
        </thead>
        <tbody>
        {% for u in user %}
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.nom }}</td>
                <td>{{ u.prenom }}</td>
                <td>{{ u.email }}</td>
                <td>{{ u.password }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">{{ 'user.userAucun'|trans }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}